server:
  port: 12080
  servlet:
    session:
      timeout: 7200


#数据连接配置
#spring:
#  datasource:
#    username: root
#    password: sqlpass
#    url: jdbc:mysql://121.196.127.220/m_labour?serverTimezone=UTC&characterEncoding=utf-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://121.196.127.220/m_labour?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
          username: root
          password: sqlpass
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://121.196.127.220/m_environment?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
          username: root
          password: sqlpass
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_2:
          url: jdbc:mysql://121.196.127.220/m_warning?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
          username: root
          password: sqlpass
          driver-class-name: com.mysql.cj.jdbc.Driver

    #druid连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#配置SQL日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:  classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#开发环境开启swagger页面访问
swagger:
  enable: false


#日志
logging:
  config: classpath:logback-spring.xml


qiniu:
  accessKey: E6GhovGh8oS1GL1n6n3TyEaDhnZk7J4IOZaFsbeD
  secretKey: VfPtGrPNtmFRM6Neo2k_Wn3biHgM6D8QebhTiEdY
  # 对象储存
  bucket: spikefree10gb # 空间名称
  zone: huadong # 存储区域
  domain: qw89j0oyx.hd-bkt.clouddn.com # 访问域名